name = "meetme-generator"
main = "src/index.js"
compatibility_date = "2025-09-24"
compatibility_flags = ["nodejs_compat"]

[images]
binding = "IMAGES"

[env.production]
name = "meetme-generator"

[observability.logs]
enabled = true
